## importing tensorflow as tf


In [2]:
import tensorflow as tf 
print(tf.version)

<module 'tensorflow._api.v2.version' from 'c:\\Users\\gamer\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>


Tensors are multi-dimensional arrays with a uniform type (called a dtype ). You can see all supported dtypes at tf. dtypes . If you're familiar with NumPy, tensors are (kind of) like np. arrays


In [3]:
# init a tensors 
x = tf.constant(4 , shape=(1,1) , dtype=tf.float32)
print(x)
# x is the now has the shape of 1 x 1 matrix

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [4]:
x = tf.constant([[2,3,4], [1,43,3]])
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 2,  3,  4],
       [ 1, 43,  3]])>

In [5]:
# creating a 3 X 3 matrix of ones type int 
x = tf.ones((3,3) , dtype=tf.int16)
 
# 2x2 matrix of zeros type float 
y = tf.zeros((2,2), dtype=tf.float32)
print(x , y)

tf.Tensor(
[[1 1 1]
 [1 1 1]
 [1 1 1]], shape=(3, 3), dtype=int16) tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)


In [6]:
# identity matrix is tf.eye()

x = tf.eye(4) 
x

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [7]:
# standard distrubution 
x = tf.random.normal((3,3) , mean=1 , stddev=1)
x


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 2.0533319 ,  1.6124858 ,  2.1573143 ],
       [ 2.5079498 , -0.3384683 , -0.34112167],
       [ 1.0644053 , -0.22773111, -1.6774228 ]], dtype=float32)>

In [8]:
x = tf.range(start=1 , limit=11 , delta=2) # delta is th e steps
x

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9])>

## math operation 


In [9]:
x = tf.constant([1,2,3])
y = tf.constant([4,5,6])

tf.subtract(x,y) 
tf.add(x,y)
tf.divide(x,y)
tf.multiply(x,y)
 

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4, 10, 18])>

In [10]:
# dot product 

tf.tensordot(x , y , axes=1)

<tf.Tensor: shape=(), dtype=int32, numpy=32>

In [11]:
x = tf.random.normal((2,3) , dtype=tf.float32) 
y = tf.random.normal((3,4) , dtype=tf.float32)
tf.matmul(x,y)

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[-1.5512795 , -0.22302312, -0.8471505 , -1.3654966 ],
       [-0.5665128 ,  0.74568135, -1.4980954 ,  1.0280446 ]],
      dtype=float32)>

# indexing 


In [12]:
x = tf.constant([1,2,3,4,5,6])
ind = tf.constant([1,3])  
tf.gather(x ,ind  )

x = tf.constant([[2,3,4],
                 [2,1,2]
                 ])
tf.gather(x ,  )


TypeError: Missing required positional argument

## neural network sequential and functional API


In [5]:
from tensorflow import keras
from tensorflow.keras import layers 


In [7]:
#importing the dataset : 
from tensorflow.keras.datasets import mnist 

In [8]:
(x_train , y_train) ,(x_test , y_test) = mnist.load_data()

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 5s 0us/step


In [9]:
print(x_train.shape , y_train.shape )   

(60000, 28, 28) (60000,)


In [13]:
# flatten the data to fit a layer in the NN 
x_train = x_train.reshape(-1,28*28).astype("float32") /  255.0   
x_train.shape

(60000, 784)

In [15]:
x_test = x_test.reshape(-1 ,28*28).astype("float32") /  255.0 
x_test.shape 

(10000, 784)

# Sequential (very convenient not flexible ) 
    - alows only one input mapped to one output

In [27]:
model = keras.Sequential(
    [
       
        layers.Dense(512 , activation='relu'),
        layers.Dense(256 , activation='relu'),
        layers.Dense(10),
    ]
)



In [18]:
model.compile(
    loss = keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(),
    metrics=['accuracy']

)

In [20]:
model.fit(x_train,y_train,batch_size=32,epochs=5,verbose=2)

Epoch 1/5
1875/1875 - 7s - 4ms/step - accuracy: 0.9439 - loss: 0.1843
Epoch 2/5
1875/1875 - 6s - 3ms/step - accuracy: 0.9748 - loss: 0.0807
Epoch 3/5
1875/1875 - 6s - 3ms/step - accuracy: 0.9825 - loss: 0.0554
Epoch 4/5
1875/1875 - 6s - 3ms/step - accuracy: 0.9861 - loss: 0.0419
Epoch 5/5
1875/1875 - 7s - 4ms/step - accuracy: 0.9894 - loss: 0.0325


In [23]:
model.evaluate(x_test,y_test,batch_size=32,verbose=2) 

313/313 - 0s - 1ms/step - accuracy: 0.0892 - loss: 2.5361


[2.536090850830078, 0.08919999748468399]

In [1]:
model.summary()

NameError: name 'model' is not defined